# accrue:generated
# accrue:fingerprint: 7b2ed27746fa30f31f0603e369e23e68a43f949bdedbced45a0c3badb71529fe
defmodule AccrueHost.Billing do
  @moduledoc """
  Host-owned billing facade generated by `mix accrue.install`.

  Keep host policy hooks here and leave processor normalization to Accrue.
  """

  import Ecto.Query, only: [from: 2]

  alias Accrue.Billing
  alias Accrue.Billing.Customer
  alias Accrue.Billing.Subscription
  alias AccrueHost.Accounts.Scope
  alias AccrueHost.Repo

  @admin_roles [:owner, :admin]

  # Host policy hook: authorize who may subscribe this billable.
  def subscribe(billable, price_id, opts \\ []) do
    Billing.subscribe(billable, price_id, opts)
  end

  # Host policy hook: enforce plan-change rules before delegating.
  def swap_plan(subscription, price_id, opts) do
    Billing.swap_plan(subscription, price_id, opts)
  end

  # Host policy hook: decide immediate cancellation vs grace-period flows.
  def cancel(subscription, opts \\ []) do
    Billing.cancel(subscription, opts)
  end

  # Host policy hook: preload or scope billable ownership if needed.
  def customer_for(billable) do
    Billing.customer(billable)
  end

  # Host policy hook: expose current billing state without teaching UI code
  # about direct Accrue schema/Repo access.
  def billing_state_for(billable) do
    customer = find_customer(billable)
    subscription = current_subscription(customer)

    {:ok, %{customer: customer, subscription: subscription}}
  end

  # Host policy hook: collect location repair input through the public
  # Accrue tax-location API instead of teaching the UI about processor details.
  def update_customer_tax_location(billable, attrs) when is_map(attrs) do
    with {:ok, customer} <- customer_for(billable) do
      Billing.update_customer_tax_location(customer, attrs)
    end
  end

  def organization_from_scope!(%Scope{} = scope) do
    case organization_from_scope(scope) do
      {:ok, organization} -> organization
      {:error, :no_active_organization} -> raise ArgumentError, "scope has no active organization"
    end
  end

  def customer_for_scope(%Scope{} = scope) do
    with {:ok, organization} <- organization_from_scope(scope) do
      customer_for(organization)
    end
  end

  def billing_state_for_scope(%Scope{} = scope) do
    with {:ok, organization} <- organization_from_scope(scope) do
      billing_state_for(organization)
    end
  end

  def subscribe_active_organization(%Scope{} = scope, price_id, opts \\ []) do
    with {:ok, organization} <- organization_from_scope(scope),
         :ok <- authorize_billing_mutation(scope) do
      subscribe(organization, price_id, opts)
    end
  end

  def update_active_organization_tax_location(%Scope{} = scope, attrs) when is_map(attrs) do
    with {:ok, organization} <- organization_from_scope(scope),
         :ok <- authorize_billing_mutation(scope) do
      update_customer_tax_location(organization, attrs)
    end
  end

  def cancel_active_organization(%Scope{} = scope, %Subscription{} = subscription, opts \\ []) do
    with {:ok, %{subscription: %Subscription{id: current_id}}} <- billing_state_for_scope(scope),
         :ok <- authorize_billing_mutation(scope),
         true <- current_id == subscription.id do
      cancel(subscription, opts)
    else
      false -> {:error, :forbidden}
      {:ok, %{subscription: nil}} -> {:error, :forbidden}
      {:error, _reason} = error -> error
    end
  end

  defp organization_from_scope(%Scope{active_organization: nil}),
    do: {:error, :no_active_organization}

  defp organization_from_scope(%Scope{active_organization: organization}), do: {:ok, organization}

  defp authorize_billing_mutation(%Scope{active_organization: nil}),
    do: {:error, :no_active_organization}

  defp authorize_billing_mutation(%Scope{membership: %{role: role}})
       when role in @admin_roles,
       do: :ok

  defp authorize_billing_mutation(%Scope{}), do: {:error, :forbidden}

  defp find_customer(%{__struct__: mod, id: id}) do
    billable_type = mod.__accrue__(:billable_type)
    owner_id = to_string(id)

    from(customer in Customer,
      where: customer.owner_type == ^billable_type and customer.owner_id == ^owner_id,
      limit: 1
    )
    |> Repo.one()
  end

  defp current_subscription(nil), do: nil

  defp current_subscription(%Customer{id: customer_id}) do
    from(subscription in Subscription,
      where: subscription.customer_id == ^customer_id,
      order_by: [desc: subscription.inserted_at],
      limit: 1
    )
    |> Repo.one()
  end
end
