# accrue:generated
# accrue:fingerprint: 7b2ed27746fa30f31f0603e369e23e68a43f949bdedbced45a0c3badb71529fe
defmodule AccrueHost.Billing do
  @moduledoc """
  Host-owned billing facade generated by `mix accrue.install`.

  Keep host policy hooks here and leave processor normalization to Accrue.
  """

  import Ecto.Query, only: [from: 2]

  alias Accrue.Billing
  alias Accrue.Billing.Customer
  alias Accrue.Billing.Subscription
  alias AccrueHost.Repo

  # Host policy hook: authorize who may subscribe this billable.
  def subscribe(billable, price_id, opts \\ []) do
    Billing.subscribe(billable, price_id, opts)
  end

  # Host policy hook: enforce plan-change rules before delegating.
  def swap_plan(subscription, price_id, opts) do
    Billing.swap_plan(subscription, price_id, opts)
  end

  # Host policy hook: decide immediate cancellation vs grace-period flows.
  def cancel(subscription, opts \\ []) do
    Billing.cancel(subscription, opts)
  end

  # Host policy hook: preload or scope billable ownership if needed.
  def customer_for(billable) do
    Billing.customer(billable)
  end

  # Host policy hook: expose current billing state without teaching UI code
  # about direct Accrue schema/Repo access.
  def billing_state_for(billable) do
    customer = find_customer(billable)
    subscription = current_subscription(customer)

    {:ok, %{customer: customer, subscription: subscription}}
  end

  defp find_customer(%{__struct__: mod, id: id}) do
    billable_type = mod.__accrue__(:billable_type)
    owner_id = to_string(id)

    from(customer in Customer,
      where: customer.owner_type == ^billable_type and customer.owner_id == ^owner_id,
      limit: 1
    )
    |> Repo.one()
  end

  defp current_subscription(nil), do: nil

  defp current_subscription(%Customer{id: customer_id}) do
    from(subscription in Subscription,
      where: subscription.customer_id == ^customer_id,
      order_by: [desc: subscription.inserted_at],
      limit: 1
    )
    |> Repo.one()
  end
end
