# accrue:generated
# accrue:fingerprint: 7b2ed27746fa30f31f0603e369e23e68a43f949bdedbced45a0c3badb71529fe
defmodule AccrueHost.Billing do
  @moduledoc """
  Host-owned billing facade generated by `mix accrue.install`.

  Keep host policy hooks here and leave processor normalization to Accrue.
  """

  alias Accrue.Billing

  # Host policy hook: authorize who may subscribe this billable.
  def subscribe(billable, price_id, opts \\ []) do
    Billing.subscribe(billable, price_id, opts)
  end

  # Host policy hook: enforce plan-change rules before delegating.
  def swap_plan(subscription, price_id, opts) do
    Billing.swap_plan(subscription, price_id, opts)
  end

  # Host policy hook: decide immediate cancellation vs grace-period flows.
  def cancel(subscription, opts \\ []) do
    Billing.cancel(subscription, opts)
  end

  # Host policy hook: preload or scope billable ownership if needed.
  def customer_for(billable) do
    Billing.customer(billable)
  end
end
