defmodule Accrue.Repo.Migrations.RevokeAccrueEventsWrites do
  @moduledoc """
  Generated by `mix accrue.install` — edit the role name to match your
  Postgres application user, then run `mix ecto.migrate`.

  Belt-and-suspenders defense in depth (D-09, D-10): the
  `accrue_events_immutable_trigger` in `create_accrue_events.exs` blocks
  UPDATE/DELETE at the row level. This REVOKE migration additionally
  strips the raw grants from the application role so a future DBA cannot
  accidentally re-enable mutations by disabling the trigger.

  NOTE: A Postgres superuser can still bypass both the trigger and the
  REVOKE grants. Documented residual risk — the install guide warns
  operators to run application workloads under a dedicated, non-superuser
  role.
  """

  use Ecto.Migration

  # EDIT ME: replace `accrue_app` with the Postgres role your application
  # connects as (e.g., the user in your `config/runtime.exs` Repo config).
  @app_role "accrue_app"

  def up do
    execute(revoke_sql())
  end

  def down do
    execute(grant_sql())
  end

  defp revoke_sql do
    events_table = Accrue.Migration.qualified_table(:accrue_events)

    """
    DO $$
    BEGIN
      IF to_regrole('#{@app_role}') IS NOT NULL THEN
        EXECUTE 'REVOKE UPDATE, DELETE, TRUNCATE ON #{events_table} FROM #{@app_role}';
      END IF;
    END
    $$;
    """
  end

  defp grant_sql do
    events_table = Accrue.Migration.qualified_table(:accrue_events)

    """
    DO $$
    BEGIN
      IF to_regrole('#{@app_role}') IS NOT NULL THEN
        EXECUTE 'GRANT UPDATE, DELETE, TRUNCATE ON #{events_table} TO #{@app_role}';
      END IF;
    END
    $$;
    """
  end
end
