defmodule Mix.Tasks.AccrueAdmin.Assets.BuildTest do
  use ExUnit.Case, async: false

  import ExUnit.CaptureIO

  alias Mix.Tasks.AccrueAdmin.Assets.Build

  defmodule FakeRunner do
    @behaviour Build.Runner

    @impl true
    def run("npx", ["--yes", tool | args], opts) do
      send(self(), {:runner_call, tool, args, opts[:cd]})

      output_path =
        case tool do
          "tailwindcss@3.4.17" -> keyword_value(args, "--output")
          "esbuild@0.25.3" -> prefixed_value(args, "--outfile=")
        end

      File.mkdir_p!(Path.dirname(output_path))
      File.write!(output_path, "generated by #{tool}")
      {:ok, 0}
    end

    defp keyword_value(args, flag) do
      index = Enum.find_index(args, &(&1 == flag))
      Enum.at(args, index + 1)
    end

    defp prefixed_value(args, prefix) do
      args
      |> Enum.find(&String.starts_with?(&1, prefix))
      |> String.replace_prefix(prefix, "")
    end
  end

  setup do
    Mix.Task.reenable("accrue_admin.assets.build")

    prior = Application.get_env(:accrue_admin, :accrue_admin_assets_build_runner)
    Application.put_env(:accrue_admin, :accrue_admin_assets_build_runner, FakeRunner)

    on_exit(fn ->
      Mix.Task.reenable("accrue_admin.assets.build")

      if prior do
        Application.put_env(:accrue_admin, :accrue_admin_assets_build_runner, prior)
      else
        Application.delete_env(:accrue_admin, :accrue_admin_assets_build_runner)
      end
    end)

    :ok
  end

  test "rebuilds css and js through the package-local runner" do
    output =
      capture_io(fn ->
        Build.run([])
      end)

    assert_received {:runner_call, "tailwindcss@3.4.17", tailwind_args, cwd}
    assert_received {:runner_call, "esbuild@0.25.3", esbuild_args, ^cwd}
    assert Enum.member?(tailwind_args, Path.join(cwd, "assets/css/app.css"))
    assert Enum.any?(esbuild_args, &String.starts_with?(&1, "--outfile="))
    assert File.read!(Path.join(cwd, "priv/static/accrue_admin.css")) =~ "tailwindcss"
    assert File.read!(Path.join(cwd, "priv/static/accrue_admin.js")) =~ "esbuild"
    assert output =~ "Rebuilt AccrueAdmin assets"
  end
end
