[
  {"lib/accrue_admin/dev/email_preview_live.ex", "The guard clause can never succeed."},
  {"lib/accrue_admin/live/connect_account_live.ex",
   "The pattern pattern _ = __value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/accrue_admin/live/connect_accounts_live.ex",
   "The pattern pattern _ = __value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/accrue_admin/live/coupon_live.ex",
   "The pattern pattern <__amount_minor@1, __currency@1> can never match the type, because it is covered by previous clauses."},
  {"lib/accrue_admin/live/coupon_live.ex",
   "The pattern pattern _ = __value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/accrue_admin/live/coupons_live.ex",
   "The pattern pattern <__amount_minor@1, __currency@1> can never match the type, because it is covered by previous clauses."},
  {"lib/accrue_admin/live/coupons_live.ex",
   "The pattern pattern _ = __value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/accrue_admin/live/promotion_code_live.ex",
   "The pattern pattern _ = __value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/accrue_admin/live/promotion_codes_live.ex",
   "The pattern pattern _ = __value@1 can never match the type, because it is covered by previous clauses."},
  {"lib/accrue_admin/router.ex", "Function Mix.env/0 does not exist."},
  {"lib/mix/tasks/accrue_admin.assets.build.ex",
   "Callback info about the Mix.Task behaviour is not available."},
  {"lib/mix/tasks/accrue_admin.assets.build.ex", "Function Mix.Task.run/1 does not exist."},
  {"lib/mix/tasks/accrue_admin.assets.build.ex", "Function Mix.shell/0 does not exist."},
  {"lib/mix/tasks/accrue_admin.assets.build.ex", "Function Mix.raise/1 does not exist."},
  {"lib/mix/tasks/accrue_admin.e2e.server.ex",
   "Callback info about the Mix.Task behaviour is not available."},
  {"lib/mix/tasks/accrue_admin.e2e.server.ex", "Function Mix.Task.run/1 does not exist."}
]
