defmodule AccrueHost.InstallBoundaryTest do
  use ExUnit.Case, async: false

  import ExUnit.CaptureIO

  @moduletag :phase10

  setup do
    Mix.shell(Mix.Shell.Process)
    on_exit(fn -> Mix.shell(Mix.Shell.IO) end)
    :ok
  end

  test "public installer patches a Phoenix host fixture with webhook and admin boundaries" do
    root = tmp_app!("install_boundary")

    write_mix_project!(root)
    write_router!(root)
    write_config!(root)

    output =
      capture_io(fn ->
        cd_preserving_code_path!(root, fn ->
          Mix.Task.clear()

          Mix.Tasks.Accrue.Install.run([
            "--yes",
            "--billable",
            "MyApp.Accounts.User",
            "--billing-context",
            "MyApp.Billing",
            "--admin-mount",
            "/billing",
            "--webhook-path",
            "/webhooks/stripe"
          ])
        end)
      end)

    assert output =~ "Accrue installer"
    assert output =~ "billing_context: MyApp.Billing"
    assert output =~ "admin_mount: /billing"
    assert output =~ "Project: Accrue.Install.Project"

    assert read!(root, "mix.exs") =~ "{:accrue, path: \"../../accrue\"}"
    assert read!(root, "mix.exs") =~ "{:accrue_admin, path: \"../../accrue_admin\"}"
    assert read!(root, "lib/my_app_web/router.ex") =~ "accrue_webhook \"/stripe\", :stripe"
    assert read!(root, "lib/my_app_web/router.ex") =~ ~s(accrue_admin "/billing")
    assert read!(root, "lib/my_app/billing.ex") =~ "generated by `mix accrue.install`"
  end

  defp tmp_app!(name) do
    root =
      Path.join(System.tmp_dir!(), "accrue_host_#{name}_#{System.unique_integer([:positive])}")

    File.rm_rf!(root)
    File.mkdir_p!(Path.join(root, "lib/my_app_web"))
    File.mkdir_p!(Path.join(root, "config"))
    root
  end

  defp write_mix_project!(root) do
    write!(
      root,
      "mix.exs",
      """
      defmodule MyApp.MixProject do
        use Mix.Project

        def project do
          [
            app: :my_app,
            version: "0.1.0",
            elixir: "~> 1.17",
            deps: deps()
          ]
        end

        def application, do: [extra_applications: [:logger]]

        defp deps do
          [
            {:phoenix, "~> 1.8"},
            {:accrue, path: "../../accrue"},
            {:accrue_admin, path: "../../accrue_admin"}
          ]
        end
      end
      """
    )
  end

  defp write_router!(root) do
    write!(
      root,
      "lib/my_app_web/router.ex",
      """
      defmodule MyAppWeb.Router do
        use MyAppWeb, :router

        pipeline :browser do
          plug :accepts, ["html"]
        end

        scope "/", MyAppWeb do
          pipe_through :browser
        end
      end
      """
    )
  end

  defp write_config!(root) do
    write!(root, "config/config.exs", "import Config\n")
  end

  defp write!(root, relative_path, content) do
    path = Path.join(root, relative_path)
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, content)
  end

  defp read!(root, relative_path) do
    root
    |> Path.join(relative_path)
    |> File.read!()
  end

  defp cd_preserving_code_path!(root, fun) when is_function(fun, 0) do
    original_path = :code.get_path()

    try do
      File.cd!(root, fun)
    after
      restore_code_path(original_path)
    end
  end

  defp restore_code_path(original_path) do
    current_path = :code.get_path()

    Enum.each(current_path -- original_path, &:code.del_path/1)

    original_path
    |> Enum.reverse()
    |> Enum.each(&:code.add_patha/1)
  end
end
