#!/usr/bin/env bash
# Verify @doc since: annotations render as badges in generated ExDoc HTML — not literal @since junk text.
# Gate: at least 7 since-badge occurrences in Accrue.Analytics.Dunning HTML; zero bare @since " lines.
# Catches regressions like bare @since "x.y.z" inside heredoc bodies (produces junk text in rendered docs).
set -euo pipefail

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT/accrue"

DUNNING_HTML="doc/Accrue.Analytics.Dunning.html"

# Skip mix docs if HTML already exists (e.g. after a preceding mix docs step in CI).
if [ ! -f "$DUNNING_HTML" ]; then
  mix docs --quiet 2>/dev/null
fi
if [ ! -f "$DUNNING_HTML" ]; then
  echo "FAIL: $DUNNING_HTML not generated by mix docs"
  exit 1
fi

SINCE_COUNT=$(grep -c 'since 1\.' "$DUNNING_HTML" 2>/dev/null || echo 0)
if [ "$SINCE_COUNT" -lt 7 ]; then
  echo "FAIL: Expected ≥7 since-badge occurrences in Dunning HTML, found $SINCE_COUNT"
  exit 1
fi

if grep -q '@since "' "$DUNNING_HTML" 2>/dev/null; then
  echo "FAIL: Literal @since junk text found in rendered ExDoc HTML — annotation not in canonical @doc since: form"
  exit 1
fi

echo "OK: ExDoc @doc since: badges verified ($SINCE_COUNT occurrences, 0 junk lines)"
