defmodule AccrueAdmin.ComponentKitchenLiveTest do
  use AccrueAdmin.LiveCase, async: false

  test "renders the shared component kitchen and floating toolbar", %{conn: conn} do
    conn = Phoenix.ConnTest.init_test_session(conn, admin_token: "admin")

    assert {:ok, _view, html} = live(conn, "/billing/dev/components")

    assert html =~ "Billing health: Unhealthy"
    assert html =~ "Primary action: open the invoice queue and collect to $0.00."
    assert html =~ "Critical: $592.50 overdue now; healthy threshold $0.00"
    assert html =~ "Step 1: work invoice queue to $0.00"
    assert html =~ "Primary action"
    assert html =~ "Secondary action"
    assert html =~ "More billing actions"
    assert html =~ "View dunning funnel and at-risk"
    assert html =~ "Dashboard"
    assert html =~ "Dev-only webhook fixtures"
    assert html =~ "/billing/dev/fake-inspect"
    assert html =~ "Command palette motion specimen"
    assert html =~ "ax-command-palette"
    assert html =~ "Billing health and recovery drawer"
    assert html =~ "Billing needs attention now"
    assert html =~ "$592.50 open exposure; target $0.00"
    assert html =~ "Billing health verdict"
    assert html =~ "ax-dev-group-drawer-primary-actions"
    assert html =~ "Open recovery analytics"
    assert html =~ "Who did what, when?"
    assert html =~ "Collect open invoices first"
    assert html =~ "Debug failed webhooks end-to-end"
    assert html =~ "Open Events audit log"
    assert html =~ "View dunning funnel"
    assert html =~ "Audit timestamp: Jul 09, 2026 14:51 UTC"
    refute html =~ "Find one customer and open billing 360 detail"
    refute html =~ "Find one customer - open 360"
    assert html =~ "View full audit history"
    assert html =~ "billing.contact.updated"
    assert html =~ "Open failed-webhook debugger"
    assert html =~ "Open invoice queue"
    assert html =~ "2 invoices ready for inline queue review"
    assert html =~ "Failed webhook deliveries"
    assert html =~ "Recovery stage"
    assert html =~ "View at-risk accounts"
    assert html =~ "invoice.payment_failed"
    assert html =~ "Northstar Labs"
    assert html =~ "$420.00 open"
    assert html =~ "Invoices queue"
    refute html =~ "Work invoice queue in this billing alert"
    assert html =~ "Open invoice queue"
    assert html =~ "Who did what, when? Actor-filtered audit log"
    assert html =~ "Open failed-webhook debugger"
    assert html =~ "Open recovery analytics"
    assert html =~ "Open invoice queue"
    assert html =~ "Customer lookup specimen"
    assert html =~ "Enter the organization slug or platform owner scope"
  end
end
